metrics-address: ":8080"
log-level: info
development-mode: false
features:
  enabled: true
  label-selectors:
    - name: "nais.io/attest"
      value: "true"
cosign:
  key-ref: ""
  ignore-tlog: false
  local-image: false
storage:
  api: http://localhost:9001/api/v1/bom
  api-key: my-api-key
identity:
  issuer: my-issuer
  project-id: my-project-id