apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "picante.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "picante.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "picante.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: DOCKER_CONFIG
              value: /etc/docker-credentials
          {{- if contains "fss" .Values.config.cluster }}
            - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
              value: /etc/root-json/.root.json
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/root-json
              name: root-json
            - mountPath: /etc/cosign
              name: config-volume
            - mountPath: "/etc/picante"
              name: picante-config
            - mountPath: /.sigstore
              name: writable-tmp
            - mountPath: /etc/docker-credentials
              name: docker-credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: writable-tmp
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ include "picante.fullname" . }}
        - name: picante-config
          secret:
            secretName: {{ include "picante.fullname" . }}
            optional: true
        - name: root-json
          secret:
            optional: true
            defaultMode: 420
            items:
              - key: .root.json
                path: root.json
            secretName: tuf-root-8-json
        - name: docker-credentials
          secret:
            defaultMode: 420
            items:
              - key: .dockerconfigjson
                path: config.json
            optional: true
            secretName: picante-docker-credentials
