apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "picante.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "picante.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "picante.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/cosign
              name: config-volume
            - name: picante-config
              mountPath: "/etc/picante"
            - mountPath: /.sigstore
              name: writable-tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: writable-tmp
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ include "picante.fullname" . }}
        - name: picante-config
          secret:
            secretName: {{ include "picante.fullname" . }}
            optional: true