apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "picante.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "picante.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "picante.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: DOCKER_CONFIG
              value: /etc/docker-credentials
          {{- if .Values.webproxy }}
            - name: HTTP_PROXY
              value: http://webproxy.nais:8088
            - name: http_proxy
              value: http://webproxy.nais:8088
            - name: HTTPS_PROXY
              value: http://webproxy.nais:8088
            - name: https_proxy
              value: http://webproxy.nais:8088
            - name: NO_PROXY
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io,.aivencloud.com,.intern.dev.nav.no
            - name: no_proxy
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io,.aivencloud.com,.intern.dev.nav.no
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/cosign
              name: config-volume
            - mountPath: "/etc/picante"
              name: picante-config
            - mountPath: /.sigstore
              name: writable-tmp
            - mountPath: /etc/docker-credentials
              name: docker-credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: writable-tmp
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ include "picante.fullname" . }}
        - name: picante-config
          secret:
            secretName: {{ include "picante.fullname" . }}
            optional: true
        - name: docker-credentials
          secret:
            defaultMode: 420
            items:
              - key: .dockerconfigjson
                path: config.json
            optional: true
            secretName: picante-docker-credentials
