apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "picante.fullname" . }}-apiserver
spec:
  egress:
      to:
        - ipBlock:
            cidr: {{ .Values.apiserverIP }}/32
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              {{- include "dependencytrack.selectorLabels" . | nindent 14 }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
---
{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1" }}
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name }}-fqdn
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - fqdns:
          {{- range $key, $value := .Values.fqdns }}
            - {{ $value }}
          {{- end }}
            - {{ .Values.backend.ingress }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress
{{- end }}