kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "slsa-verde.labels" . | nindent 4 }}
  name: {{ include "slsa-verde.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - replicasets
      - daemonsets
      - jobs
      - statefulsets
    verbs:
      - list
      - get
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "slsa-verde.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: "{{ .Release.Namespace }}"
---
