apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "picante.name" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.google.serviceAccountEmail }}