apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slsa-verde.name" . }}
  labels:
    {{- include "slsa-verde.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.google.serviceAccountEmail }}