apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
stringData:
  picante.yaml: |
    features:
      enabled: {{ .Values.config.features.enabled }}
      label-selectors:
        {{- range $key, $value := .Values.config.features.labelSelectors }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
    cosign:
      key-ref: {{ .Values.config.cosign.keyRef }}
    storage:
      api: {{ .Values.config.storage.api }}
      api-key: {{ .Values.config.storage.apiKey }}
    identities:
      {{- range $key, $value := .Values.config.identities }}
      - issuer: {{ $value.issuer }}
        subject-reg-exp: {{ $value.subjectRegExp | quote }}
      {{- end }}