apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
stringData:
  dependencytrack_username: "{{ .Values.config.dependencytrack.username }}"
  dependencytrack_password: "{{ .Values.config.dependencytrack.password }}"
  cosign_key_ref: "{{ .Values.config.cosign.keyRef }}"