apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
stringData:
  picante.yaml: |
    features:
      enabled: {{ .Values.config.features.enabled }}
      label-selectors:
        {{- range $key, $value := .Values.config.features.labelSelectors }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
    cosign:
      {{- .Values.config.cosign | toYaml | nindent 6 }}
    storage:
    {{- .Values.config.storage | toYaml | nindent 6 }}
    identities:
      {{- range $key, $value := .Values.config.identities }}
      - issuer: {{ $value.issuer }}
        subject-reg-exp: {{ $value.subjectRegExp | quote }}
      {{- end }}
    teamIdentity:
      {{- .Values.config.teamIdentity | toYaml | nindent 6 }}