apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "picante.fullname" . }}
  labels:
    {{- include "picante.labels" . | nindent 4 }}
stringData:
  picante.yaml: |
    features:
      {{- if .Values.config.features.enabled }}
      label-selectors:
        {{- .Values.config.features.labelSelectors | toYaml | nindent 8 }}
      {{- end }}
    cosign:
      {{- .Values.config.cosign | toYaml | nindent 6 }}
    storage:
    {{- .Values.config.storage | toYaml | nindent 6 }}
    identities:
    {{- .Values.config.identities | toYaml | nindent 6 }}
    github:
    {{- .Values.config.github | toYaml | nindent 6 }}
    teamIdentity:
    {{- .Values.config.teamIdentity | toYaml | nindent 6 }}
    cluster: {{ .Values.config.cluster }}