apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "slsa-verde.fullname" . }}-docker-credentials
stringData:
  ".dockerconfigjson": {{ .Values.dockerconfigjson | quote }}
