apiVersion: apps/v1
kind: Deployment
metadata:
  name: picanteapp1
  labels:
    app.kubernetes.io/name: picanteapp1
    team: picante
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: picanteapp1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: picanteapp1
        team: picante
        nais.io/attest: "true"
    spec:
      containers:
        - name: picanteapp1
          image: "ttl.sh/salsa/gogoogletestapp:1h"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi

