apiVersion: apps/v1
kind: Deployment
metadata:
  name: picanteapp1
  labels:
    app.kubernetes.io/name: picanteapp1
    team: nais-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: picanteapp1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: picanteapp1
        team: nais-system
        nais.io/salsa-verify-attestation: "true"
        #nais.io/salsa-key-ref: "true" # default false (true|false)
        #nais.io/salsa-predicate: "cyclonedx" # default cyclonedx (lsaprovenance|link|spdx|spdxjson|cyclonedx|vuln|custom)
        #nais.io/salsa-keyless-provider: "google" # default google, (google|github)
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: picanteapp1
          image: "europe-north1-docker.pkg.dev/nais-io/nais/images/picante:sha-9260627"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

