development-mode: true
features:
  enabled: false
cosign:
  key-ref: hack/kms-pub
storage:
  api: http://localhost:9001
  username: admin
  password: yolo
  team: Administrators
github:
  organizations:
    - nais
    - navikt
identities:
  - issuer: https://accounts.google.com
    subject-reg-exp: ".*@nais-io.iam.gserviceaccount.com"
teamIdentity:
  issuer: "https://accounts.google.com"
  domain: "plattformsikkerhet-dev-496e.iam.gserviceaccount.com"