metrics-address: ":8080"
development-mode: true
features:
  enabled: true
  label-selectors:
    - name: "nais.io/salsa-verify-attestation"
      value: "true"
cosign:
  key-ref: /picante/kms.pub
storage:
  api: http://localhost:9001/api/v1
  api-key: my-api-key
identity:
  issuer: my-issuer
  project-id: my-project-id