metrics-address: ":8080"
development-mode: true
features:
  enabled: true
  label-selectors:
    - name: "nais.io/salsa-verify-attestation"
      value: "true"
cosign:
  key-ref: /picante/kms.pub
storage:
  api: http://localhost:9001/api/v1
  api-key: my-api-key
identities:
  - issuer: https://provider.com
    subjectRegExp: ".*@som-subject.com"
  - issuer: https://provider2.com
    subjectRegExp: ".*@som-subject2.com"