environmentKinds:
  - management
  - tenant
  - legacy
  - onprem
values:
  config.logLevel:
    displayName: Log level
    config:
      type: string
  webproxy:
    displayName: Enable webproxy
    computed:
      template: '{{ eq .Kind "onprem" }}'
  apiserverIP:
    displayName: API server IP
    computed:
      template: '"{{.Env.apiserver_endpoint}}"'
  config.cluster:
    displayName: Current cluster
    computed:
      template: '"{{.Env.name}}"'
  config.github.organizations:
    description: Required GitHub organizations to verify image attestations, a comma seperated list
    displayName: GitHub organization(s)
    computed:
      template: |
        {{ if or (eq .Tenant.Name "nav") (eq .Tenant.Name "dev-nais") }}
          "nais,navikt"
        {{ else }}
          "nais,{{.Tenant.Name}}"
        {{ end }}
    config:
      type: string
  config.dependencytrack.password:
    displayName: dependencytrack API password
    computed:
      template: '"{{.Management.picante_dependencytrack_password}}"' # TODO change to slsa_verde
  config.dependencytrack.api:
    displayName: dependencytrack API endpoint
    computed:
      # TODO revert to dependencytrack-backend
      template: |
        {{ if eq .Kind "management" }}
          "http://dependencytrack-test-backend:8080"
        {{ else }}
          "https://dependencytrack-test-backend.{{.Tenant.Name}}.cloud.nais.io"
        {{ end }}
  dockerconfigjson:
    displayName: Docker config json
    required: true
    config:
      type: string
      secret: true
  google.serviceAccountEmail:
    displayName: Google service account email
    computed:
      template: '"{{.Env.slsa_verde_service_account}}"'
    config:
      type: string
  image.tag:
    displayName: Image tag
    config:
      type: string
