apiserverIP:

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  name: picante
  tag: 20230414-090558-6aaa3f2

team: nais

webproxy: false

resources:
  requests:
    cpu: 50m
    memory: 2Gi

dockerconfigjson:

google:
  serviceAccountEmail:

fqdns:
  - ttl.sh
  - sigstore-tuf-root.storage.googleapis.com
  - europe-north1-docker.pkg.dev

config:
  features:
    enabled: false
    labelSelectors:
      name: nais.io/salsa-verify-attestation
      value: "true"
  cluster: test
  cosign:
    keyRef:
  storage:
    api: http://dependencytrack-backend:8080
    username: picante
    password:
    team: Administrators
  identities: [ ]
  teamIdentity:
    issuer:
    domain:
  github:
    organizations: [ ]

kms:
  pubKey: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUxgOVWCBlCTpJcKKJxQTLBAkp5F9
    /rKmU0cIhHkBJmbPLcDtmoDX0fX7d9OzpK7eLyBg+c/rRcQgGvZvBCLRKQ==
    -----END PUBLIC KEY-----