apiserverIP:

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  name: picante
  tag: 20230414-090558-6aaa3f2

team: nais

resources:
  requests:
    cpu: 100m
    memory: 256Mi

config:
  features:
    enabled: true
    labelSelectors:
      "nais.io/salsa-verify-attestation": "true"
  cosign:
    keyRef: /etc/cosign/kms.pub
  storage:
    ingress:
    api: http://dependencytrack-backend
    apiKey:
  identities:
    - issuer:
      subjectRegExp:
    - issuerRegExp:
      subject:
  teamIdentity:
    prefix:
    issuer:
    domain:
  kmsPubKey: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUxgOVWCBlCTpJcKKJxQTLBAkp5F9
    /rKmU0cIhHkBJmbPLcDtmoDX0fX7d9OzpK7eLyBg+c/rRcQgGvZvBCLRKQ==
    -----END PUBLIC KEY-----