name: Dependabot PR Check

on:
  pull_request:
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/chart.yaml'
      - '*.md'

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images

jobs:
  test-dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
      - run: go test -cover ./...
      - name: Vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...